---
title: "Weekly Mosquito Surveillance and Forecast Report"
author: Florida Department of Health in Alachua County
output:
  pdf_document:
    highlight: zenburn
    toc: yes
  html_document:
    theme: united
    toc: yes
graphics: yes

---

\begin{center}
Joe Brew \\
Ben Brew \\
Yoni Teitelbaum
\end{center}

```{r, echo = FALSE}
library(knitr)
opts_chunk$set(comment=NA, warning = FALSE, message = FALSE, echo = FALSE)
```

```{r}
# wd <- '/home/joebrew/Documents/mosquito15/'
# setwd(wd)
library(png)
library(grid)
library(ggplot2)
load('../checkpoint.RData')
```

```{r, fig = TRUE, fig.height = 0.5, echo=FALSE, fig.align = 'center'}
img <- readPNG('../images/logo.png')
grid.raster(img)
```

# Overview

This is a main header with important stuff under it.

```{r}
g <- ggplot(data = future_agg) + 
  aes(x = date, y = predicted) +
  theme_bw() +
#   geom_line(aes(x = date, y = lower ), color = 'red') +
#   geom_line(aes(x = date, y = upper ), color = 'red') +
  geom_ribbon(aes(x = date, y = upper, ymin = lower, ymax = upper), alpha = 0.5) +
  geom_line(color = 'darkred', lwd = 3) + 
  xlab('Date') + 
  ylab('Mosquitos')
g 
```

# Most recent collection details

This is a sub-header.

# Forecast details

I don't even know if this will render.